// One clear line per HQ tab: what it is, what you do there. Rendered as the tab's header.
export const TAB_INFO = {
  launch: ['Launch & setup', 'Hook up keys, then sign the one-time launch config. Everything launchable is mapped here.', ['Launch map', 'Presets', 'Readiness check']],
  fees: ['Trading & fees', 'The FEELESS fee on every trade: rate, engine, fee accounts and live earnings.', ['Fee %', 'Engine', 'Fee accounts']],
  latency: ['Lag catcher', 'What real visitors feel: slow routes, janky pages, and the fix for each.', ['Speed score', 'Lite effects', 'Fix list']],
  nfts: ['NFTs', 'Your cards as Solana collections on Metaplex Core, Crossmint or Underdog, dropped to any wallets or to everyone holding the card.', ['Create collection', 'Drop to holders']],
  money: ['Money', 'Every FEELESS wallet in one place: fee accounts + splits, the season reserve and badge pools, and Circle wallets. One live pulse feeds it all.', ['Treasury & splits', 'Reserve & badge pools', 'Circle wallets']],
  numbers: ['Numbers', 'Growth at a glance: users, trades, volume, retention.', []],
  traffic: ['Traffic', 'Where visitors come from and which pages they use.', []],
  pulse: ['Pulse', 'Live activity across chat, calls and trades.', []],
  marketing: ['Marketing', 'Shareable FeeCat posts and GIFs built from real trades.', ['Posts', 'GIFs']],
  kols: ['KOLs', 'Callers ranked by what their calls actually did.', []],
  invites: ['Invites', 'Referral codes and who they brought in.', []],
  ads: ['Ads', 'Sponsored slots and what they earn.', []],
  ideas: ['Ideas', 'Feature ideas from the community.', []],
  holders: ['Holders', 'Every holder of your coins. Select wallets to airdrop or badge.', ['Select', 'Airdrop', 'Badge']],
  studio: ['Airdrop Studio', 'Build a drop, simulate it, send from your wallet.', []],
  airdrops: ['Scheduled drops', 'Drops waiting to go out, and their on-chain receipts.', []],
  snapshots: ['Snapshots', 'Freeze a holder list at a moment in time.', []],
  badges: ['Badges', 'Award badges and decide what % of which pool each badge earns.', ['Reserve pool', 'Badge × pool matrix', 'Award']],
  seasons: ['Seasons', 'Season themes, weeks, prizes and the reserve wallet.', []],
  pools: ['Pools', 'Create a locked TOKEN/SOL pool for a token that already exists.', ['Create pool', 'Verify pool']],
  feecat: ['Fee 🐱', "FeeCat's trading brain: rules, what she's learning, and her results.", ['Brain', 'Lessons', 'Book']],
  broadcast: ['Broadcast', 'Message everyone at once (site banner / push).', []],
  investigate: ['Intel desk', 'The reputation department: ruggers, snipers, bundlers, their funders and crews, with each one\'s likely next move. FeeCat and the rug shield read the same database.', []],
  verify: ['Verify coins', 'Run the verification checks, grant the gold check or revoke one.', ['Run checks', 'Grant', 'Revoke']],
  overview: ['Security', 'Platform health, keys and risks at a glance.', []],
  mod: ['Moderation', 'Reports, mutes and the blocklist.', []],
  access: ['Access', 'Who can open this HQ.', []],
  bugs: ['Bugs', 'Crash reports and bug tickets, newest first.', []],
};
