import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Download, FileText, ArrowUpRight, Check, Activity, Wallet, ShieldCheck } from 'lucide-react';
import { useMarket } from '../../hooks/useMarket';
import { useWorkspace, CONTEXTS } from '../../hooks/useWorkspace';
import { useWallet } from '../../hooks/useWallet';
import { FeelessMark } from '../FeelessLogo';
import { FeeBackFlow } from './FeeBack';
import { Tokenomics } from './FeeCommand';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '../ui/dialog';
import { PdfReader } from './PdfReader';

const WhitepaperContents = () => {
  const { data, error } = useMarket('/api/docs/whitepaper', 0);
  const base = `${process.env.REACT_APP_BACKEND_URL}/api/docs/whitepaper.pdf`;
  return <article className="document-page command-whitepaper"><div className="document-header"><FeelessMark size={68} /><span className="draft-label" data-testid="whitepaper-version">WHITEPAPER / VERSION {data?.version || '1.0'}</span><h1>FEELESS<span>Less Noise. More Alpha.</span></h1><p>A FeeLess Future.</p><div className="whitepaper-actions"><a className="btn-primary" data-testid="whitepaper-download-pdf" href={`${base}?download=true`}><Download size={15} />Download PDF</a><a className="btn-outline" data-testid="whitepaper-view-pdf" href={base} target="_blank" rel="noreferrer"><FileText size={15} />View whitepaper PDF</a></div><small>Same source document as this web edition. Policy, implementation status and risks disclosed.</small></div>{error && <p className="market-error" data-testid="whitepaper-error">{error}</p>}{data && <><div className="contract-registry"><span className="eyebrow">OWNER-SUPPLIED / SOLANA CONTRACT REGISTRY</span>{data.contracts.map(c => <a key={c.name} data-testid={`whitepaper-contract-${c.name.toLowerCase()}`} href={`https://solscan.io/token/${c.mint}`} target="_blank" rel="noreferrer"><b>{c.name}</b><code>{c.mint}</code><ArrowUpRight size={13} /></a>)}</div><div className="document-body"><nav className="document-toc">{data.chapters.map(c => <a key={c.id} data-testid={`whitepaper-toc-${c.number}`} href={`#${c.id}`}><span>{String(c.number).padStart(2, '0')}</span>{c.title}</a>)}</nav><div>{data.chapters.map(c => <section id={c.id} key={c.id}><span className="eyebrow">{String(c.number).padStart(2, '0')} / FEELESS</span><h2>{c.title}</h2><p data-testid={`whitepaper-chapter-${c.number}`}>{c.text}</p></section>)}</div></div></>}</article>;
};

export const CommandWhitepaper = () => {
  const [preview, setPreview] = useState(false);
  const pdf = `${process.env.REACT_APP_BACKEND_URL}/api/docs/whitepaper.pdf`;
  return <div data-testid="whitepaper-workspace" onClickCapture={event => {
    if (event.target.closest?.('[data-testid="whitepaper-view-pdf"]')) { event.preventDefault(); setPreview(true); }
  }}><WhitepaperContents /><Dialog open={preview} onOpenChange={setPreview}><DialogContent className="pdf-preview-dialog" data-testid="whitepaper-pdf-dialog"><DialogTitle>FEELESS / Whitepaper</DialogTitle><DialogDescription>Version 1.0 · The same source as the interactive web edition.</DialogDescription><PdfReader url={pdf} /><div className="pdf-preview-actions"><a className="btn-primary" data-testid="pdf-dialog-download" href={`${pdf}?download=true`}><Download size={14} />Download PDF</a><a className="btn-outline" data-testid="pdf-dialog-open-direct" href={pdf} target="_blank" rel="noreferrer">Open file directly<ArrowUpRight size={14} /></a></div></DialogContent></Dialog></div>;
};

const MISSIONS = [
  ['01', 'The connected foundation', 'LIVE', 'Globe, provider-backed discovery, public polling chat and source-labelled charts.'],
  ['02', 'The command layer', 'TESTING', '$FEE heartbeat, persistent contexts, Alpha Tape, conditional alerts and rich CA intelligence.'],
  ['03', 'Wallet execution', 'TESTING', 'Jupiter routing, explicit Phantom signing, simulation and independent confirmation checks.'],
  ['04', 'Fee-Back settlement', 'PLANNED', 'Published eligibility rules, fee provenance, valuation policy, audited distribution and replay protection.'],
  ['05', 'Public platform launch', 'PLANNED', 'Target: Q2 2027. Dependent on validation, provider readiness and security work. Not a guarantee.'],
];
export const MissionRoadmap = () => {
  const [filter, setFilter] = useState('ALL');
  return <div className="document-page mission-roadmap"><div className="command-page-title"><span className="eyebrow">FEELESS / MISSION CONTROL</span><h1>A future in progress.</h1><p>Public platform launch target <b>Q2 2027</b>. Targets are not guarantees.</p></div><div className="mission-filters">{['ALL', 'PLANNED', 'BUILDING', 'TESTING', 'LIVE'].map(v => <button className={filter === v ? 'active' : ''} data-testid={`roadmap-filter-${v.toLowerCase()}`} key={v} onClick={() => setFilter(v)}>{v}</button>)}</div><div className="mission-timeline">{MISSIONS.filter(m => filter === 'ALL' || m[2] === filter).map(([n, title, state, text]) => <section key={n} className={`mission-${state.toLowerCase()}`} data-testid={`mission-${n}`}><div className="mission-node"><span>{n}</span><i /></div><div><span className="state-tag">{state}</span><h2>{title}</h2><p>{text}</p></div></section>)}{!MISSIONS.some(m => filter === 'ALL' || m[2] === filter) && <div className="truth-empty" data-testid="roadmap-filter-empty">No milestone currently carries this status.</div>}</div></div>;
};

export const UnderstandFeeless = () => {
  const [layer, setLayer] = useState('platform');
  const layers = { platform: ['FEELESS', 'The platform connects discovery, intelligence, trading tools and community.'], fee: ['$FEE', 'The core ecosystem asset. Price and candles require real provider markets.'], feeback: ['FEE-BACK', 'The intended economic fee-return system: 100% of eligible tracked USD fee value in FEECAT equivalent.'], feecat: ['FEECAT', 'The culture, community and intended Fee-Back delivery layer.'], globe: ['GLOBE', 'The ecosystem map. Network context carries into the entire terminal.'], trenches: ['TRENCHES', 'Real conversations connected to verified contract lookups and market intelligence.'] };
  return <div className="document-page"><div className="command-page-title"><span className="eyebrow">UNDERSTAND FEELESS</span><h1>One system.<br /><em>Connected layers.</em></h1></div><div className="learning-layers">{Object.entries(layers).map(([id, [name]]) => <button key={id} data-testid={`learn-layer-${id}`} className={layer === id ? 'active' : ''} onClick={() => setLayer(id)}>{name}</button>)}</div><div className="learning-layer-detail" data-testid="learn-layer-detail"><FeelessMark size={64} /><div><h2>{layers[layer][0]}</h2><p>{layers[layer][1]}</p></div></div><FeeBackFlow /><Tokenomics /><div className="learning-disclosure"><ShieldCheck size={23} /><div><h2>The real rule: never invent the signal.</h2><p>A new pool is not necessarily a new token. An indexed contract is not an audit. A quoted fee is not an eligible settled fee. A calculator is not a payout.</p><Link to="/terminal/whitepaper" data-testid="learn-full-whitepaper">Read the complete whitepaper<ArrowUpRight size={14} /></Link></div></div></div>;
};

export const TerminalConfiguration = ({ settings, setSettings, onWallet }) => {
  const { ecosystem, setEcosystem } = useWorkspace(); const { wallet } = useWallet();
  const { data } = useMarket('/api/trading/status', 0);
  const update = (key, value) => setSettings({ ...settings, [key]: value });
  return <div className="document-page terminal-config"><div className="command-page-title"><span className="eyebrow">TERMINAL CONFIGURATION</span><h1>Your environment.<br /><em>Your edge.</em></h1></div><div className="config-grid"><section><h2><Wallet size={17} />Wallet & networks</h2><button data-testid="config-wallet" className="btn-outline" onClick={onWallet}>{wallet ? `${wallet.name} · manage connection` : 'Connect wallet'}</button><label>Active ecosystem<select data-testid="config-active-ecosystem" value={ecosystem.id} onChange={e => setEcosystem(e.target.value)}>{CONTEXTS.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Default ecosystem<select data-testid="config-default-ecosystem" value={settings.defaultEcosystem || 'solana'} onChange={e => { update('defaultEcosystem', e.target.value); localStorage.setItem('feeless-default-ecosystem', e.target.value); }}>{CONTEXTS.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></section><section><h2><Activity size={17} />Providers</h2><dl><div><dt>Market snapshots</dt><dd>DexScreener</dd></div><div><dt>Pools & OHLCV</dt><dd>GeckoTerminal</dd></div><div><dt>Solana routing</dt><dd data-testid="config-jupiter-status">{data?.configured ? 'Jupiter · configured' : 'Checking configuration'}</dd></div><div><dt>Confirmation</dt><dd>Solana mainnet RPC</dd></div></dl><p>Availability is checked per request. Credentials remain server-side.</p></section><section><h2>Appearance & charts</h2><label>Data density<select data-testid="config-density" value={settings.compact ? 'compact' : 'comfortable'} onChange={e => update('compact', e.target.value === 'compact')}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Default candle interval<select data-testid="config-chart-interval" value={settings.chartInterval || '1h'} onChange={e => update('chartInterval', e.target.value)}>{['5m', '15m', '1h', '4h', '1d'].map(t => <option key={t}>{t}</option>)}</select></label><label className="config-toggle">Reduced motion<input data-testid="settings-reduced-motion" type="checkbox" checked={settings.reducedMotion} onChange={e => update('reducedMotion', e.target.checked)} /></label><label className="config-toggle">Discovery auto-refresh<input data-testid="settings-autorefresh" type="checkbox" checked={settings.autoRefresh} onChange={e => update('autoRefresh', e.target.checked)} /></label></section><section><h2><ShieldCheck size={17} />Privacy & alerts</h2><p>Watchlists, conditional alerts, learning progress and preferences live in this browser. Public chat and transaction references are stored server-side.</p><p>Alerts evaluate only while this terminal is open. No background push or email notifications are enabled.</p><Link className="btn-outline" data-testid="config-alerts-link" to="/terminal/alerts">Manage conditional alerts<ArrowUpRight size={14} /></Link></section></div></div>;
};