import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDown, ArrowUpRight, Coins, Cat, Check, Play, Wallet, ShieldCheck, Activity } from 'lucide-react';
import { useWallet } from '../../hooks/useWallet';
import { useMarket } from '../../hooks/useMarket';
import { formatUSD } from '../../lib/dexscreener';
import { FeelessMark } from '../FeelessLogo';
const STEPS = [
  ['TRADE', 'A user approves a transaction. Normal network, DEX and provider fees may apply.'],
  ['FEE DETECTED', 'Actual settled fee data is sourced from the transaction or eligible provider record. A quote is not a settled fee.'],
  ['ELIGIBILITY VERIFIED', 'Published program rules determine which fees qualify. These rules are not activated yet.'],
  ['USD VALUE RECORDED', 'The eligible fee value is recorded in USD, with its source and transaction reference.'],
  ['FEECAT EQUIVALENT CALCULATED', 'Eligible USD value is divided by the verified FEECAT reference price at the defined distribution point.'],
  ['FEECAT DISTRIBUTED', 'The qualifying wallet receives the calculated FEECAT amount. No distributions are currently activated.'],
  ['FEE-BACK COMPLETE', 'A verifiable distribution transaction completes the record. FEECAT value can change after receipt.'],
];

export const FeeBackFlow = () => {
  const [step, setStep] = useState(0);
  return <section className="fee-flow"><div className="command-section-title"><span><Activity size={16} />THE RETURN PATH</span><small>ARCHITECTURE EXPLORER / PLANNED</small></div><div className="flow-track">{STEPS.map(([label], i) => <button key={label} onClick={() => setStep(i)} data-testid={`feeback-flow-step-${i}`} className={`${i === step ? 'current' : ''} ${i < step ? 'visited' : ''}`}><span>{String(i + 1).padStart(2, '0')}</span><b>{label}</b>{i < STEPS.length - 1 && <i />}</button>)}</div><div className="flow-explanation" data-testid="feeback-flow-description"><span>0{step + 1}</span><p>{STEPS[step][1]}</p><button data-testid="feeback-flow-next" onClick={() => setStep(s => (s + 1) % STEPS.length)} title="Next architecture step"><ArrowUpRight size={18} /></button></div><small className="provider-note">This animation explains the intended mechanism. It does not represent a real transaction, eligibility decision or payout.</small></section>;
};

export const FeeBackCalculator = ({ feeCat, compact = false }) => {
  const [eligible, setEligible] = useState('60');
  const amount = Number(eligible); const valid = eligible !== '' && Number.isFinite(amount) && amount >= 0;
  const price = feeCat?.status === 'market_observed' && !feeCat.stale ? Number(feeCat.pair?.priceUsd) : null;
  return <section className={`feeback-calculator ${compact ? 'compact-calculator' : ''}`}><div className="command-section-title"><span><Coins size={16} />FEE-BACK VISION</span><small>ILLUSTRATIVE CALCULATOR / NOT A PAYOUT</small></div><div className="calculator-input"><label htmlFor={compact ? 'fee-illustration-compact' : 'fee-illustration'}>Eligible tracked fees · example USD</label><span>$<input id={compact ? 'fee-illustration-compact' : 'fee-illustration'} data-testid={compact ? 'feeback-example-input-compact' : 'feeback-example-input'} inputMode="decimal" type="number" min="0" step="0.01" value={eligible} onChange={e => setEligible(e.target.value)} /></span></div><div className="calculator-return"><span>100% ELIGIBLE FEE VALUE</span><strong data-testid={compact ? 'feeback-dollar-equivalent-compact' : 'feeback-dollar-equivalent'}>{valid ? formatUSD(amount) : '—'}</strong><small>equivalent in FEECAT at distribution</small></div><div className="calculator-detail"><span>FEECAT quantity</span><b data-testid={compact ? 'feeback-token-equivalent-compact' : 'feeback-token-equivalent'}>{valid && price > 0 ? `≈ ${(amount / price).toLocaleString('en-US', { maximumFractionDigits: 6 })}` : 'Awaiting verified reference price'}</b></div><p>Quantity = eligible USD ÷ verified FEECAT USD price. {price > 0 ? 'This current-market illustration is not a distribution quote.' : 'No FEECAT price is assumed.'} The official distribution point and rules are not activated.</p></section>;
};

export const FeeBackPreview = ({ quote, feeCat }) => <section className="fee-preview"><div className="command-section-title"><span><Cat size={15} />FEE-BACK PREVIEW</span><span className="state-tag amber">PLANNED</span></div><dl><div><dt>Trade value</dt><dd>{formatUSD(quote?.swapUsdValue ?? quote?.inputValue)}</dd></div><div><dt>Network signature fee · estimate</dt><dd>{quote?.signatureFeeLamports != null ? `${Number(quote.signatureFeeLamports) / 1e9} SOL` : 'Unavailable'}</dd></div><div><dt>DEX / route fee</dt><dd>{quote?.feeBps != null ? `${quote.feeBps} bps · ${quote.feeMint || 'provider fee mint'}` : 'Provider dependent'}</dd></div><div><dt>Eligible FEELESS fee</dt><dd>Not yet determined</dd></div><div><dt>Estimated FEECAT distribution</dt><dd>Not activated</dd></div></dl><p>100% of qualifying tracked fee value is intended to return in FEECAT. Normal fees still apply. Eligibility, reference pricing and distribution rules must be activated first.</p><Link data-testid="swap-feeback-rules" to="/terminal/feeback">View the economic model<ArrowUpRight size={12} /></Link></section>;

export const FeeBackCenter = ({ feeCat }) => {
  const { wallet } = useWallet();
  const { data: history } = useMarket(wallet?.chain === 'solana' ? `/api/trading/history/${wallet.address}` : null, 30000);
  return <div className="fee-back-center"><div className="command-page-title"><span className="eyebrow">THE ECONOMIC FEE-RETURN LAYER</span><h1>The fees come back.<br /><em>The story moves forward.</em></h1><p>100% of eligible tracked fees. Equivalent dollar value. Delivered through FeeCat under program rules.</p><span className="state-tag amber">PROGRAM PLANNED · NO PAYOUTS ACTIVATED</span></div><div className="fee-back-summary">{[['ELIGIBLE TRACKED FEES', 'Awaiting rules'], ['PENDING FEECAT', 'Not activated'], ['COMPLETED DISTRIBUTIONS', 'No verified records'], ['REFERENCE PRICE', feeCat?.status === 'market_observed' ? 'Distribution point undefined' : 'Awaiting verified market']].map(([label, value], i) => <div key={label}><small>{label}</small><strong data-testid={`feeback-summary-${i}`}>{value}</strong></div>)}</div><FeeBackFlow /><div className="feeback-two-col"><FeeBackCalculator feeCat={feeCat} /><section className="program-rules"><span className="eyebrow">THE IMPORTANT DISTINCTION</span><h2>Economically fee-less.<br />Not magically gas-free.</h2><p>Network, DEX and provider fees can still apply. Fee-Back records eligible USD value and returns its FEECAT equivalent at a defined distribution point.</p><ul><li>Eligibility is not automatic for every fee.</li><li>Quoted fees are not settled fee records.</li><li>FEECAT can change in value after distribution.</li><li>No guaranteed profit, yield or future value.</li></ul><Link data-testid="feeback-whitepaper-link" to="/terminal/whitepaper">Read the full architecture<ArrowUpRight size={14} /></Link></section></div><section className="distribution-history"><div className="command-section-title"><span>TRANSACTION REFERENCES</span><small>APPLICATION-SUBMITTED SWAPS / NOT REWARDS</small></div>{!wallet && <div className="truth-empty" data-testid="feeback-wallet-required"><Wallet size={24} /><span>Connect your wallet to view its application transaction references.</span></div>}{wallet && !history?.transactions?.length && <div className="truth-empty" data-testid="feeback-history-empty">No verified application transaction references for this wallet.</div>}{history?.transactions?.map(tx => <a data-testid={`feeback-transaction-${tx.order_id}`} key={tx.order_id} target="_blank" rel="noreferrer" href={`https://solscan.io/tx/${tx.signature}`}><span>{tx.state}</span><code>{tx.signature.slice(0, 20)}…</code><ArrowUpRight size={14} /></a>)}</section></div>;
};

export const FeeCatCenter = ({ asset, community, onSelect }) => {
  const [mission, setMission] = useState(() => localStorage.getItem('feecat-learning-step') || 'culture');
  const choose = v => { setMission(v); localStorage.setItem('feecat-learning-step', v); };
  const text = { culture: 'The first cat of FEELESS. A shared identity built around curiosity, participation and on-chain culture.', community: 'The Trenches connect real participants. No purchased-looking activity, fabricated messages or imaginary users.', utility: 'The intended delivery asset for eligible USD-equivalent Fee-Back. Distribution infrastructure and rules remain planned.' };
  return <div className="feecat-command"><div className="feecat-banner" style={{ backgroundImage: "url('/assets/feecat-bg.png')" }}><div className="feecat-banner-copy"><span className="eyebrow">THE FIRST CAT OF FEELESS</span><h1>Fun. Culture.<br /><em>More for you.</em></h1><p>The community layer. The culture layer.<br />The Fee-Back delivery layer.</p><span className="state-tag amber" data-testid="feecat-launch-state">{asset?.status === 'market_observed' ? 'MARKET OBSERVED · DISTRIBUTIONS PLANNED' : 'AWAITING MARKET · DISTRIBUTIONS PLANNED'}</span></div><div className="feecat-insignia"><img src="/assets/feecat-mark.png" alt="FEECAT cat mark" /><span>FEECAT</span></div></div><div className="fee-back-summary">{[['FEECAT RECEIVED', 'No verified distributions'], ['TREASURY STATUS', 'Not published / unverified'], ['COMMUNITY / 7 DAYS', community?.messages != null ? `${community.messages} actual messages` : 'Connecting'], ['CURRENT MARKET', asset?.status === 'market_observed' ? formatUSD(asset.pair?.priceUsd) : 'Awaiting provider market']].map(([k, v], i) => <div key={k}><small>{k}</small><strong data-testid={`feecat-stat-${i}`}>{v}</strong></div>)}</div><div className="feecat-lore"><div className="lore-tabs">{Object.keys(text).map(k => <button data-testid={`feecat-lore-${k}`} key={k} onClick={() => choose(k)} className={mission === k ? 'active' : ''}>{k}</button>)}</div><h2>{mission === 'culture' ? 'A little mischief. A real purpose.' : mission === 'community' ? 'A community, not a counter.' : 'Culture meets the return path.'}</h2><p data-testid="feecat-lore-text">{text[mission]}</p><Link to={mission === 'community' ? '/terminal/chat' : mission === 'utility' ? '/terminal/feeback' : '/terminal/learn'} data-testid="feecat-mission-action">{mission === 'community' ? 'Join your ecosystem room' : mission === 'utility' ? 'Explore Fee-Back' : 'Understand FEELESS'}<ArrowUpRight size={16} /></Link><small>Learning missions are local navigation progress, not token entitlements.</small></div><FeeBackFlow /><FeeBackCalculator feeCat={asset} />{asset?.pair && <button className="btn-primary" data-testid="feecat-open-market" onClick={() => onSelect(asset.pair)}>Open FEECAT market<ArrowUpRight size={16} /></button>}</div>;
};