import React, { useState } from 'react';

// Bump this only when the terms/privacy text materially changes — returning users are asked again only then.
export const LEGAL_VERSION = '2026-09-26';
export const LEGAL_CONTACT = 'the FEELESS team via the official FEELESS channels';
const KEY = 'feeless:legal-consent';
let memoryAccepted = false; // fallback when browser storage is blocked, so we never nag within a visit

function accepted() {
  if (memoryAccepted) return true;
  try { return JSON.parse(localStorage.getItem(KEY) || 'null')?.v === LEGAL_VERSION; } catch { return false; }
}

export function LegalConsent() {
  const [open, setOpen] = useState(() => !accepted());
  if (!open) return null;
  const accept = () => {
    memoryAccepted = true;
    try { localStorage.setItem(KEY, JSON.stringify({ v: LEGAL_VERSION, at: new Date().toISOString() })); } catch { /* storage blocked */ }
    setOpen(false);
  };
  return <div className="legal-consent" role="dialog" aria-modal="false" aria-labelledby="legal-title" data-testid="legal-consent">
    <b id="legal-title">Before you trench 🌿</b>
    <p>FEELESS is a non-custodial crypto terminal. Nothing here is financial advice; crypto is high-risk and you can lose everything. We never hold your keys or funds. We store only what you choose to make public (wallet address, profile, chat posts, verified trade receipts) and use browser storage for your settings — no ad trackers, no selling data. You must be 18+ and allowed to use crypto where you live.</p>
    <div><a href="/terminal/legal" target="_blank" rel="noopener noreferrer">Privacy &amp; Terms</a><button type="button" className="btn-primary" onClick={accept} data-testid="legal-accept">Got it</button></div>
  </div>;
}

export function LegalPage() {
  return <article className="legal-page" data-testid="legal-page">
    <h1>Privacy Policy &amp; Terms</h1>
    <p className="legal-meta">Version {LEGAL_VERSION} · Applies to the FEELESS web app.</p>
    <h2>1. What FEELESS is</h2>
    <p>FEELESS is a non-custodial interface for viewing public blockchain data and routing swaps through third-party protocols (for example Jupiter). You sign every transaction in your own wallet. FEELESS never has custody of, or the ability to move, your funds.</p>
    <h2>2. Not financial advice · risk</h2>
    <p>Everything on FEELESS — including Fee the cat's calls and reads, reputation scores, badges, alerts and rankings — is informational and generated by rules from public data. It is not investment, financial, tax or legal advice. Tokens can go to zero, pools can be drained, and transactions are irreversible. Paper trades by FeeCats are simulations.</p>
    <h2>3. Eligibility</h2>
    <p>You must be at least 18 and legally permitted to use crypto services where you live. You may not use FEELESS if you are subject to sanctions or located in a sanctioned jurisdiction.</p>
    <h2>4. Data we process</h2>
    <ul>
      <li><b>Public by design:</b> your wallet address(es), profile fields you save, chat and wall posts, reactions, badges, and trade receipts (transaction signature, tokens moved, time). These are visible to everyone and much of it is already public on-chain.</li>
      <li><b>Signatures:</b> message signatures prove wallet ownership. Signing a message never moves funds. A chat session token is stored in your browser for up to 7 days.</li>
      <li><b>Operational:</b> IP addresses are used transiently for rate-limiting and abuse prevention and are not stored with your profile. Aggregate click counts on tickers/contract addresses are stored without identifying you.</li>
      <li><b>Browser storage:</b> settings, watchlist, theme and this consent choice live in your browser's local storage. We use no advertising or cross-site tracking cookies.</li>
      <li><b>Third parties:</b> market data and routing come from providers such as DexScreener, GeckoTerminal, Jupiter and Solana RPC providers; your requests to them are subject to their policies.</li>
    </ul>
    <h2>5. Your rights</h2>
    <p>Depending on where you live (e.g. GDPR in the EU/UK, CCPA/CPRA in California) you may request access to, correction of, or deletion of off-chain data tied to your wallet (profile, posts, badges). You can edit your profile and delete posts on your wall at any time. On-chain data cannot be altered or deleted by anyone. We do not sell personal information. To make a request, contact {LEGAL_CONTACT}.</p>
    <h2>6. Community rules</h2>
    <p>No scams, impersonation, phishing links, harassment, or illegal content. Evidence-based blocklisting of snipers/bundlers reflects on-chain behaviour. We may remove content or restrict features to protect users.</p>
    <h2>7. Fees</h2>
    <p>Any FEELESS fee is shown before you sign a swap. Network and third-party protocol fees are separate.</p>
    <h2>8. No warranty · liability</h2>
    <p>FEELESS is provided "as is" without warranties. Data can be delayed or wrong. To the maximum extent permitted by law, FEELESS is not liable for losses arising from your use of the app, smart contracts, third-party protocols, or market movements.</p>
    <h2>9. Changes</h2>
    <p>If these terms change materially, the version date above changes and you'll be asked once to acknowledge the new version.</p>
  </article>;
}
