import React from 'react';
import { Link } from 'react-router-dom';
import { Download, ArrowUpRight, Check, Clock } from 'lucide-react';
import { FeelessMark } from '../FeelessLogo';
import { normalizeAutoRefresh, normalizeCompact, normalizeReducedMotion } from './LocalTools';

const SECTIONS = [
  ['The thesis', 'Crypto moves across ecosystems, launchpads and communities. FEELESS brings discovery into one workspace: a visual ecosystem globe, live market snapshots, pool charts, watchlists and public chat. Less noise. More context.'],
  ['What is live', 'The globe connects chains and launchpad directories. The terminal reads DexScreener search and pair data, plus GeckoTerminal trending pools, new pools and OHLCV candles. Chat is persisted in MongoDB and refreshed by polling. Watchlists and price alerts are stored locally in your browser.'],
  ['Data & market coverage', 'Provider feeds are limited snapshots, not an exhaustive index of all coins or launches. A new pool is not necessarily a newly created token. Pool age is the age returned by the provider. Rankings apply only to the fetched feed. Market capitalisation may be unavailable; fully diluted valuation (FDV) is labelled separately. Cached or unavailable data is explicitly marked. Prices are not execution quotes.'],
  ['Wallets & execution', 'Injected Phantom (Solana) and EVM browser wallets can expose an account after your approval. FEELESS does not request signatures, hold private keys, submit transactions, execute trades or verify your identity. Trading and token creation links open external providers, whose fees and policies apply.'],
  ['Fees, token & economics', 'There is no platform trading fee charged by this discovery interface because it does not execute trades. Blockchain network fees, exchange fees and external service charges are not waived. No official FEE or FeeCat contract address, token supply, allocation, launch date, reward programme or fee-back mechanism has been supplied or verified. This draft does not invent or announce tokenomics.'],
  ['Community, privacy & safety', 'Chat is public and pseudonymous, not authenticated identity. Messages, handles and attached token snapshots are stored on the server. Watchlists, alerts and display settings remain in browser storage. Token previews are historical message attachments, not endorsements. Never share seed phrases or private keys. Always verify contracts independently.'],
  ['Roadmap & limitations', 'Future work may include broader indexed-market coverage, independent contract risk analysis, authenticated moderation and optional wallet portfolio indexing. Transaction execution, launch tooling, rewards and any official token require separate product, legal and security work. Nothing in this draft is a commitment to a delivery date or investment return.'],
];

export const Whitepaper = () => {
  const download = () => {
    const content = '# FEELESS — Product Whitepaper\n\nDRAFT v0.2 — Not an offering document.\n\n' + SECTIONS.map(([h, p]) => `## ${h}\n\n${p}`).join('\n\n');
    const url = URL.createObjectURL(new Blob([content], { type: 'text/markdown' }));
    const a = document.createElement('a'); a.href = url; a.download = 'FEELESS-whitepaper-draft.md'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <article className="document-page" data-testid="whitepaper-page"><div className="document-header"><FeelessMark size={68} /><span className="draft-label" data-testid="whitepaper-draft-label">DRAFT v0.2 · PRODUCT VISION</span><h1>The signal.<br /><span>Not the noise.</span></h1><p>FEELESS ecosystem whitepaper</p><button className="btn-outline" data-testid="whitepaper-download" onClick={download}><Download size={15} />Download draft (.md)</button></div><div className="document-body"><nav className="document-toc">{SECTIONS.map(([title], i) => <a key={title} data-testid={`whitepaper-toc-${i}`} href={`#chapter-${i}`}><span>0{i + 1}</span>{title}</a>)}</nav><div>{SECTIONS.map(([title, text], i) => <section id={`chapter-${i}`} key={title}><span className="eyebrow">0{i + 1}</span><h2>{title}</h2><p data-testid={`whitepaper-chapter-${i}`}>{text}</p></section>)}</div></div></article>;
};

export const Roadmap = () => <div className="document-page"><div className="page-heading"><span className="eyebrow">BUILDING IN THE OPEN</span><h1>What's next.</h1><p>Actual progress. No invented timelines.</p></div><div className="roadmap-list">{[['01', 'The foundation', true, '3D ecosystem globe · launchpad directory · polling chat · token previews'], ['02', 'The degen workspace', true, 'Live pool discovery · candlestick charts · local watchlists · browser price alerts · read-only wallet connection'], ['03', 'A wider lens', false, 'Broader indexing · contract risk signals · wallet portfolio data · authenticated community moderation'], ['04', 'Execution, considered', false, 'Trading, token launches and any rewards programme require further validation. No launch date announced.']].map(([n, title, complete, text]) => <section key={n} data-testid={`roadmap-phase-${n}`}><span className="roadmap-number">{n}</span><div><span className={complete ? 'positive small' : 'muted small'}>{complete ? <Check size={13} /> : <Clock size={13} />}{complete ? 'AVAILABLE' : 'EXPLORING'}</span><h2>{title}</h2><p>{text}</p></div></section>)}</div></div>;

export const Learn = () => <div className="document-page"><div className="page-heading"><span className="eyebrow">KEEP YOUR EDGE</span><h1>Conviction needs context.</h1><p>Before the next ape, know what you're looking at.</p></div><div className="learning-grid">{[['01', 'A ticker is not an identity.', 'Multiple tokens can share a name. Compare the full contract address with independent official sources. A familiar logo or ticker is not verification.'], ['02', 'Liquidity is your exit.', 'Volume is traded value; liquidity is the depth available in a pool. Thin liquidity can cause severe slippage. Reported volume can be manipulated.'], ['03', 'New pool ≠ new token.', 'Providers index new liquidity pools. A long-existing token can create a new pool today. Pool age alone does not identify an early launch.'], ['04', 'Market cap vs. FDV.', 'Market cap uses circulating supply, while FDV uses fully diluted supply. If market cap is unknown, FEELESS explicitly labels the FDV estimate.'], ['05', 'Wallets never need your seed here.', 'Connecting only exposes your public address. FEELESS does not need your seed phrase, private key or a signature to explore market data.'], ['06', 'No green light is a guarantee.', 'A rising chart, active chat or launchpad listing is not due diligence. Contracts may restrict selling or enable malicious actions. Only risk what you can lose.']].map(([n, title, text]) => <section key={n}><span className="eyebrow">{n} / FIELD NOTES</span><h2>{title}</h2><p>{text}</p></section>)}</div><Link className="btn-outline" to="/terminal/whitepaper" data-testid="learn-whitepaper">Read the whitepaper<ArrowUpRight size={15} /></Link></div>;

export const SettingsPage = ({ settings, setSettings }) => {
  const compact = normalizeCompact(settings.compact);
  const autoRefresh = normalizeAutoRefresh(settings.autoRefresh);
  const reducedMotion = normalizeReducedMotion(settings.reducedMotion);
  return <div className="document-page"><div className="page-heading"><span className="eyebrow">YOUR WORKSPACE</span><h1>Make it yours.</h1><p>Preferences stay in this browser.</p></div><div className="settings-list"><label><span><b>Compact market rows</b><small>A denser view of your market feed.</small></span><input data-testid="settings-compact" type="checkbox" checked={compact} onChange={e => setSettings({ ...settings, compact: normalizeCompact(e.target.checked) })} /></label><label><span><b>Automatic market refresh</b><small>Refresh provider snapshots every 90 seconds.</small></span><input data-testid="settings-autorefresh" type="checkbox" checked={autoRefresh} onChange={e => setSettings({ ...settings, autoRefresh: normalizeAutoRefresh(e.target.checked) })} /></label><label><span><b>Reduced motion</b><small>Disable decorative interface animation.</small></span><input data-testid="settings-reduced-motion" type="checkbox" checked={reducedMotion} onChange={e => setSettings({ ...settings, reducedMotion: normalizeReducedMotion(e.target.checked) })} /></label></div><div className="risk-note">Wallets are not authenticated identities. Watchlists, settings and alerts do not sync across devices.</div></div>;
};