import React from 'react';
import { ExternalLink, Star, ArrowUpRight } from 'lucide-react';
import { Change, TokenAvatar } from './MarketPrimitives';
import { formatUSD, formatAge, pairKey, dexUrl } from '../../lib/dexscreener';

export const MarketTable = ({ pairs, onSelect, has, toggle, loading, refreshing = false, screenerLabel, prefix = 'market' }) => <div className="market-table-wrap">
  {refreshing && <div className="market-table-live-status" data-testid={`${prefix}-refreshing`}><span className="loader" />Updating live DEX coins…</div>}
  <table className="market-table" data-testid={`${prefix}-table`}><thead><tr><th>#</th><th>Token / Pool age</th><th>Price</th><th className="hide-small">1h</th><th>24h</th><th className="hide-medium">24h volume</th><th className="hide-small">Liquidity</th><th className="hide-medium">MCap / FDV</th><th>Actions</th></tr></thead><tbody>
    {loading && <tr><td colSpan={9}><div className="empty-table market-coin-loading" data-testid={`${prefix}-loading`}><span className="loader" />Loading live DEX coins…</div></td></tr>}
    {!loading && !pairs.length && <tr><td colSpan={9}><div className="empty-table" data-testid={`${prefix}-empty`}>No matching pools in this feed.</div></td></tr>}
     {!loading && pairs.map((p, i) => { const signals = p.signals || {}; const label = signals.score_label || screenerLabel || 'Unavailable'; const reasons = Array.isArray(signals.score_reasons) ? signals.score_reasons.filter(Boolean).slice(0, 3) : []; return <tr key={pairKey(p)} data-testid={`${prefix}-row-${pairKey(p)}`}><td className="muted mono">{String(i + 1).padStart(2, '0')}</td><td><button className="token-select" onClick={() => onSelect(p)} data-testid={`${prefix}-select-${pairKey(p)}`}><TokenAvatar pair={p} /><span><strong>{p.baseToken?.symbol || 'Token unavailable'}<ArrowUpRight size={11} /></strong><small>{p.chainId || 'Network unavailable'} <i>·</i> {formatAge(p.pairCreatedAt)}</small><small className="token-screening-label" data-testid={`${prefix}-score-label-${pairKey(p)}`}>{label}{signals.screener_score != null && <i> · score {signals.screener_score}</i>}</small><small className="token-screening-reasons" data-testid={`${prefix}-score-reasons-${pairKey(p)}`}>{reasons.length ? reasons.join(' · ') : 'Observed reasons unavailable'}</small></span></button></td><td className="mono" data-testid={`${prefix}-price-${pairKey(p)}`}>{formatUSD(p.priceUsd)}</td><td className="hide-small"><Change value={p.priceChange?.h1} id={`${prefix}-h1-${pairKey(p)}`} /></td><td><Change value={p.priceChange?.h24} id={`${prefix}-h24-${pairKey(p)}`} /></td><td className="mono hide-medium" data-testid={`${prefix}-volume-${pairKey(p)}`}>{formatUSD(p.volume?.h24)}</td><td className="mono hide-small" data-testid={`${prefix}-liquidity-${pairKey(p)}`}>{formatUSD(p.liquidity?.usd)}</td><td className="mono hide-medium" data-testid={`${prefix}-cap-${pairKey(p)}`}>{formatUSD(p.marketCap ?? p.fdv)}{p.marketCap == null && <small className="fdv-tag">FDV</small>}</td><td><div className="row-actions"><a data-testid={`${prefix}-dex-${pairKey(p)}`} title="Open DexScreener" href={dexUrl(p)} target="_blank" rel="noreferrer"><ExternalLink size={14} /></a><button data-testid={`${prefix}-watch-${pairKey(p)}`} title={has(p) ? 'Remove from watchlist' : 'Watch token'} onClick={() => toggle(p)} className={has(p) ? 'is-saved' : ''}><Star size={15} fill={has(p) ? 'currentColor' : 'none'} /></button></div></td></tr>; })}
  </tbody></table>
</div>;